
name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  release-tags:
    uses: brunnh1lde/SwissCaves/.github/workflows/release-tags.yml@master
    secrets: inherit
